//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_dotnet.Libraries.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurer
    {
        public string InsurerID { get; set; }
        public string UrlScheme { get; set; }
        public string LogoPath { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}
